name = "universal"
compatibility_date = "2024-09-19"
main = "./.output/server/index.mjs"
assets = { directory = "./.output/public/", binding = "ASSETS" }
routes = [
  { pattern = "universal.oroborus.org", custom_domain = true }
]

[observability]
enabled = true

[observability.logs]
enabled = true

# These definitions from the experimental cloudflare durable PR: https://github.com/nitrojs/nitro/pull/2801
[[durable_objects.bindings]]
name = "$DurableObject"
class_name = "$DurableObject"

[[migrations]]
tag = "v1"
new_classes = ["$DurableObject"]
