name = "universal"
compatibility_date = "2025-03-16"
main = "./.output/server/index.mjs"
assets = { directory = "./.output/public/", binding = "ASSETS" }
routes = [
  { pattern = "universal.oroborus.org", custom_domain = true }
]
compatibility_flags = ["nodejs_compat", "nodejs_compat_populate_process_env"]
# use the dashboard as source of truth for secrets & vars:
keep_vars = true 
upload_source_maps = true

[observability]
enabled = true

[observability.logs]
enabled = true

# These definitions from the experimental cloudflare durable PR: https://github.com/nitrojs/nitro/pull/2801
[[durable_objects.bindings]]
name = "$DurableObject"
class_name = "$DurableObject"

[[migrations]]
tag = "v1"
new_classes = ["$DurableObject"]

[[d1_databases]]
binding = "DB"
database_name = "universal"
database_id = "e12ef9e4-9c35-4dd4-87a6-fbc683ee4dda"
migrations_dir = "server/drizzle/migrations"
